import os, time, json, math, threading
from datetime import datetime, timezone, date, timedelta
from pathlib import Path
import requests
from dotenv import load_dotenv
from fastapi import FastAPI, Body, Response
from fastapi.staticfiles import StaticFiles
from sqlalchemy import create_engine, text

load_dotenv()
APP_DIR = Path(__file__).parent
DATA_DIR = APP_DIR / "data"
DATA_DIR.mkdir(exist_ok=True)
DEFAULT_DB = f"sqlite:///{DATA_DIR / 'trading_ai_elite.db'}"
DATABASE_URL = os.getenv("DATABASE_URL") or DEFAULT_DB
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

WATCHLIST_PATH = APP_DIR / "watchlist.json"
app = FastAPI(title="Trading AI Elite 2.0 Auto AI")
engine = create_engine(DATABASE_URL, pool_pre_ping=True, future=True)
CACHE = {"market_ts": 0, "market": None}
ENGINE_LOCK = threading.Lock()

DEFAULT_SETTINGS = {
    "account_size": 5000.0,
    "daily_target": 50.0,
    "daily_max_loss": 50.0,
    "risk_per_trade_pct": 0.5,
    "max_trades_per_day": 3,
    "max_open_trades": 2,
    "min_confidence": 78,
    "min_risk_reward": 1.45,
    "auto_engine_enabled": True,
    "engine_interval_seconds": 300,
    "trading_mode": "paper",
    "telegram_daily_report": True,
    "telegram_weekly_report": True,
    "report_hour_utc": 21
}

def now_iso(): return datetime.now(timezone.utc).isoformat()
def today(): return date.today().isoformat()

def q(sql, params=None, fetch=False):
    params = params or {}
    with engine.begin() as conn:
        res = conn.execute(text(sql), params)
        if fetch:
            return [dict(r._mapping) for r in res.fetchall()]
    return None

def create_table(sql_pg, sql_sqlite):
    try:
        q(sql_pg)
    except Exception:
        if DATABASE_URL.startswith("sqlite"):
            q(sql_sqlite)
        else:
            raise

def init_db():
    q("CREATE TABLE IF NOT EXISTS settings(key VARCHAR(100) PRIMARY KEY,value TEXT NOT NULL)")
    create_table(
        """CREATE TABLE IF NOT EXISTS paper_trades(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, day VARCHAR(20) NOT NULL, opened_at TEXT NOT NULL, closed_at TEXT,
        symbol VARCHAR(30) NOT NULL, name TEXT NOT NULL, group_name TEXT NOT NULL, side VARCHAR(10) NOT NULL,
        entry DOUBLE PRECISION NOT NULL, current_price DOUBLE PRECISION NOT NULL, stop DOUBLE PRECISION NOT NULL,
        target1 DOUBLE PRECISION NOT NULL, target2 DOUBLE PRECISION NOT NULL, qty DOUBLE PRECISION NOT NULL,
        confidence INTEGER NOT NULL, risk_reward DOUBLE PRECISION NOT NULL, status VARCHAR(30) NOT NULL, pnl DOUBLE PRECISION NOT NULL,
        reason TEXT NOT NULL, ai_explanation TEXT NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS paper_trades(
        id INTEGER PRIMARY KEY AUTOINCREMENT, day TEXT, opened_at TEXT, closed_at TEXT, symbol TEXT, name TEXT, group_name TEXT, side TEXT,
        entry REAL, current_price REAL, stop REAL, target1 REAL, target2 REAL, qty REAL, confidence INTEGER, risk_reward REAL,
        status TEXT, pnl REAL, reason TEXT, ai_explanation TEXT)"""
    )
    create_table(
        """CREATE TABLE IF NOT EXISTS decisions(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, ts TEXT NOT NULL, symbol VARCHAR(30) NOT NULL, name TEXT NOT NULL,
        decision VARCHAR(50) NOT NULL, confidence INTEGER NOT NULL, risk VARCHAR(20) NOT NULL, price DOUBLE PRECISION NOT NULL,
        reason TEXT NOT NULL, ai_explanation TEXT NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS decisions(
        id INTEGER PRIMARY KEY AUTOINCREMENT, ts TEXT, symbol TEXT, name TEXT, decision TEXT, confidence INTEGER, risk TEXT,
        price REAL, reason TEXT, ai_explanation TEXT)"""
    )
    create_table(
        """CREATE TABLE IF NOT EXISTS engine_runs(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, ts TEXT NOT NULL, status VARCHAR(50) NOT NULL,
        opened_trade INTEGER NOT NULL, message TEXT NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS engine_runs(
        id INTEGER PRIMARY KEY AUTOINCREMENT, ts TEXT, status TEXT, opened_trade INTEGER, message TEXT)"""
    )
    create_table(
        """CREATE TABLE IF NOT EXISTS market_snapshots(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, ts TEXT NOT NULL, total INTEGER NOT NULL,
        strong_buy INTEGER NOT NULL, strong_sell INTEGER NOT NULL, buy_watch INTEGER NOT NULL, sell_watch INTEGER NOT NULL,
        wait_count INTEGER NOT NULL, avg_confidence DOUBLE PRECISION NOT NULL, best_symbol VARCHAR(30), best_name TEXT,
        best_signal VARCHAR(50), best_confidence INTEGER, market_comment TEXT NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS market_snapshots(
        id INTEGER PRIMARY KEY AUTOINCREMENT, ts TEXT, total INTEGER, strong_buy INTEGER, strong_sell INTEGER, buy_watch INTEGER,
        sell_watch INTEGER, wait_count INTEGER, avg_confidence REAL, best_symbol TEXT, best_name TEXT, best_signal TEXT,
        best_confidence INTEGER, market_comment TEXT)"""
    )
    create_table(
        """CREATE TABLE IF NOT EXISTS automation_state(
        key VARCHAR(100) PRIMARY KEY,
        value TEXT NOT NULL
        )""",
        """CREATE TABLE IF NOT EXISTS automation_state(
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
        )"""
    )
    for k, v in DEFAULT_SETTINGS.items():
        if not q("SELECT key FROM settings WHERE key=:key", {"key": k}, fetch=True):
            q("INSERT INTO settings(key,value) VALUES(:key,:value)", {"key": k, "value": json.dumps(v)})

init_db()

def get_settings():
    rows = q("SELECT key,value FROM settings", fetch=True)
    s = DEFAULT_SETTINGS.copy()
    for r in rows:
        try: s[r["key"]] = json.loads(r["value"])
        except Exception: s[r["key"]] = r["value"]
    s["engine_interval_seconds"] = int(os.getenv("ENGINE_INTERVAL_SECONDS", s.get("engine_interval_seconds",300)))
    s["database_url_type"] = "postgresql" if DATABASE_URL.startswith("postgresql") else "sqlite"
    s["database_persistent"] = bool(os.getenv("DATABASE_URL"))
    return s

def save_settings(payload):
    for k, v in payload.items():
        if k in DEFAULT_SETTINGS:
            q("DELETE FROM settings WHERE key=:key", {"key": k})
            q("INSERT INTO settings(key,value) VALUES(:key,:value)", {"key": k, "value": json.dumps(v)})
    return get_settings()

def load_symbols():
    with open(WATCHLIST_PATH,"r",encoding="utf-8") as f:
        return json.load(f)["symbols"]

def fetch_chart(ticker, range_="1y", interval="1d"):
    r = requests.get(f"https://query1.finance.yahoo.com/v8/finance/chart/{ticker}",
                     params={"range": range_, "interval": interval},
                     headers={"User-Agent": "Mozilla/5.0"}, timeout=15)
    r.raise_for_status()
    result = r.json().get("chart",{}).get("result")
    if not result: raise ValueError("No market data")
    data=result[0]; quote=data["indicators"]["quote"][0]; rows=[]
    for i,ts in enumerate(data["timestamp"]):
        o,h,l,c = quote["open"][i], quote["high"][i], quote["low"][i], quote["close"][i]
        v = quote.get("volume",[0]*len(data["timestamp"]))[i]
        if None in (o,h,l,c): continue
        rows.append({"date": datetime.fromtimestamp(ts,timezone.utc).strftime("%Y-%m-%d"),
                     "open":float(o),"high":float(h),"low":float(l),"close":float(c),"volume":float(v or 0)})
    if len(rows) < 90: raise ValueError("Not enough history")
    return rows

def ema(vals,span):
    alpha=2/(span+1); out=vals[0]
    for v in vals[1:]: out=alpha*v+(1-alpha)*out
    return out

def sma(vals,n):
    vals=vals[-n:] if len(vals)>=n else vals
    return sum(vals)/len(vals) if vals else 0

def rsi(vals,n=14):
    gains=[]; losses=[]
    for i in range(-n,0):
        ch=vals[i]-vals[i-1]; gains.append(max(ch,0)); losses.append(abs(min(ch,0)))
    ag=sum(gains)/n; al=sum(losses)/n
    return 100 if al==0 else 100-100/(1+ag/al)

def atr(rows,n=14):
    trs=[]; prev=rows[-n-1]["close"]
    for row in rows[-n:]:
        trs.append(max(row["high"]-row["low"], abs(row["high"]-prev), abs(row["low"]-prev)))
        prev=row["close"]
    return sum(trs)/len(trs)

def macd(vals): return ema(vals[-120:],12)-ema(vals[-140:],26)

def bollinger_pos(vals,n=20):
    recent=vals[-n:]; mean=sum(recent)/len(recent)
    sd=math.sqrt(sum((x-mean)**2 for x in recent)/len(recent))
    upper=mean+2*sd; lower=mean-2*sd
    return 0.5 if upper==lower else (vals[-1]-lower)/(upper-lower)

def pct(vals,n): return 0 if len(vals)<=n else (vals[-1]/vals[-n-1]-1)*100

def candle(rows):
    last=rows[-1]; prev=rows[-2]
    body=abs(last["close"]-last["open"]); rng=max(0.0001,last["high"]-last["low"])
    upper=last["high"]-max(last["close"],last["open"])
    lower=min(last["close"],last["open"])-last["low"]
    if body/rng < 0.12: return "DOJI",0
    if lower > body*2 and upper < body: return "HAMMER",4
    if upper > body*2 and lower < body: return "SHOOTING_STAR",-4
    if last["close"]>last["open"] and prev["close"]<prev["open"] and last["close"]>prev["open"] and last["open"]<prev["close"]:
        return "BULLISH_ENGULFING",6
    if last["close"]<last["open"] and prev["close"]>prev["open"] and last["open"]>prev["close"] and last["close"]<prev["open"]:
        return "BEARISH_ENGULFING",-6
    return "NONE",0

def normalize_score(raw):
    if raw >= 92: return min(96, 88 + round((raw-92)*0.8))
    if raw <= 8: return max(4, 12 - round((8-raw)*0.8))
    return raw

def explain(name, side, signal, confidence, risk, rr, reason):
    if side=="WAIT":
        return f"{name}: WAIT. Sistem ne vidi dovoljno čist setup; potvrde se ne poklapaju dovoljno dobro."
    action = "kupovinu" if side=="BUY" else "prodaju"
    return f"{name}: sistem bira {action} jer ima {signal} setup, confidence {confidence}%, rizik {risk}, RR oko 1:{rr}. Razlozi: {reason}."

def analyze(rows, meta):
    closes=[x["close"] for x in rows]; vols=[x["volume"] for x in rows]; price=closes[-1]
    e8=ema(closes[-60:],8); e20=ema(closes[-80:],20); e50=ema(closes[-160:],50); e100=ema(closes[-220:],100); e200=ema(closes,200)
    rv=rsi(closes); av=atr(rows); mv=macd(closes); bb=bollinger_pos(closes)
    ch5=pct(closes,5); ch20=pct(closes,20); ch60=pct(closes,60)
    volavg=sma(vols,20); volfactor=vols[-1]/volavg if volavg>0 else 1
    high20=max(x["high"] for x in rows[-20:]); low20=min(x["low"] for x in rows[-20:])
    high60=max(x["high"] for x in rows[-60:]); low60=min(x["low"] for x in rows[-60:])
    pat,pscore=candle(rows)
    raw=50; bull=[]; bear=[]
    if price>e20: raw+=6; bull.append("price above EMA20")
    else: raw-=6; bear.append("price below EMA20")
    if e8>e20>e50: raw+=10; bull.append("bullish EMA stack")
    elif e8<e20<e50: raw-=10; bear.append("bearish EMA stack")
    if e50>e200: raw+=12; bull.append("primary trend bullish")
    else: raw-=12; bear.append("primary trend bearish")
    raw += 4 if e100>e200 else -4
    if mv>0: raw+=6; bull.append("MACD positive")
    else: raw-=6; bear.append("MACD negative")
    if 50<=rv<=66: raw+=8; bull.append("RSI healthy")
    elif 66<rv<=72: raw+=2; bull.append("RSI strong")
    elif rv>75: raw-=9; bear.append("RSI overbought")
    elif rv<35: raw-=9; bear.append("RSI weak/oversold")
    elif rv<45: raw-=4
    if ch5>0 and ch20>0: raw+=8; bull.append("5d and 20d momentum positive")
    elif ch5<0 and ch20<0: raw-=8; bear.append("5d and 20d momentum negative")
    raw += 5 if ch60>0 else -5
    if price>high20*0.995: raw+=4; bull.append("near 20d breakout")
    if price<low20*1.005: raw-=4; bear.append("near 20d breakdown")
    if price>high60*0.995: raw+=3; bull.append("near 60d high")
    if price<low60*1.005: raw-=3; bear.append("near 60d low")
    if volfactor>1.4: raw+=3; bull.append("volume expansion")
    if bb>0.95: raw-=4; bear.append("Bollinger high")
    if bb<0.05: raw-=2; bear.append("Bollinger low")
    raw += pscore
    if pat!="NONE": (bull if pscore>=0 else bear).append(pat)
    score=normalize_score(max(0,min(100,round(raw))))
    if score>=86: signal,side="STRONG BUY","BUY"
    elif score>=70: signal,side="BUY WATCH","BUY"
    elif score<=14: signal,side="STRONG SELL","SELL"
    elif score<=30: signal,side="SELL WATCH","SELL"
    else: signal,side="WAIT","WAIT"
    stop_dist=max(av*1.5,price*0.01); t1_dist=max(av*2.2,price*0.014); t2_dist=max(av*3.4,price*0.022)
    if side=="SELL": stop=price+stop_dist; t1=price-t1_dist; t2=price-t2_dist
    else: stop=price-stop_dist; t1=price+t1_dist; t2=price+t2_dist
    rr=abs(t1-price)/abs(price-stop) if abs(price-stop)>0 else 0
    risk="LOW" if av/price<0.025 else "MEDIUM" if av/price<0.055 else "HIGH"
    reasons=(bull if side=="BUY" else bear) if side!="WAIT" else (bull+bear)
    reason="; ".join(reasons[:9])
    ai=explain(meta["name"],side,signal,score,risk,round(rr,2),reason)
    return {"symbol":None,"name":meta["name"],"ticker":meta["ticker"],"group":meta["group"],"price":round(price,4),
            "signal":signal,"side":side,"confidence":int(score),"risk":risk,"trend":"BULLISH" if e50>e200 else "BEARISH",
            "rsi":round(rv,2),"atr":round(av,4),"macd":round(mv,4),"bollinger_pos":round(bb,2),"candle":pat,
            "ema8":round(e8,4),"ema20":round(e20,4),"ema50":round(e50,4),"ema100":round(e100,4),"ema200":round(e200,4),
            "change_5d":round(ch5,2),"change_20d":round(ch20,2),"change_60d":round(ch60,2),
            "entry":round(price,4),"stop":round(stop,4),"target1":round(t1,4),"target2":round(t2,4),"risk_reward":round(rr,2),
            "reason":reason,"ai_explanation":ai,"updated_at":now_iso()}

def log_decision(symbol,x):
    try:
        q("""INSERT INTO decisions(ts,symbol,name,decision,confidence,risk,price,reason,ai_explanation)
             VALUES(:ts,:symbol,:name,:decision,:confidence,:risk,:price,:reason,:ai)""",
          {"ts":now_iso(),"symbol":symbol,"name":x.get("name",""),"decision":x.get("signal","ERR"),
           "confidence":x.get("confidence",0),"risk":x.get("risk",""),"price":x.get("price",0),
           "reason":x.get("reason",""),"ai":x.get("ai_explanation","")})
    except Exception:
        pass

def market_comment(vals):
    total=len(vals)
    if not total: return "Nema dovoljno podataka za komentar tržišta."
    strong_buy=sum(1 for x in vals if x.get("signal")=="STRONG BUY")
    strong_sell=sum(1 for x in vals if x.get("signal")=="STRONG SELL")
    buy_watch=sum(1 for x in vals if "BUY" in x.get("signal",""))
    sell_watch=sum(1 for x in vals if "SELL" in x.get("signal",""))
    avg=sum(x.get("confidence",0) for x in vals)/total
    mood="bullish" if strong_buy>strong_sell and buy_watch>sell_watch else "bearish" if strong_sell>strong_buy and sell_watch>buy_watch else "mixed/neutral"
    return f"AI market scan: režim je {mood}. Analizirano {total} instrumenata. Strong BUY: {strong_buy}, Strong SELL: {strong_sell}, prosečan confidence {round(avg)}%."

def save_market_snapshot(out):
    vals=[x for x in out.values() if not x.get("error")]
    if not vals: return
    vals_sorted=sorted(vals, key=lambda x: x.get("confidence",0), reverse=True)
    best=vals_sorted[0]
    payload={
        "ts":now_iso(),"total":len(vals),
        "strong_buy":sum(1 for x in vals if x.get("signal")=="STRONG BUY"),
        "strong_sell":sum(1 for x in vals if x.get("signal")=="STRONG SELL"),
        "buy_watch":sum(1 for x in vals if "BUY" in x.get("signal","")),
        "sell_watch":sum(1 for x in vals if "SELL" in x.get("signal","")),
        "wait_count":sum(1 for x in vals if x.get("signal")=="WAIT"),
        "avg_confidence":sum(x.get("confidence",0) for x in vals)/len(vals),
        "best_symbol":best.get("symbol"),"best_name":best.get("name"),
        "best_signal":best.get("signal"),"best_confidence":best.get("confidence"),
        "market_comment":market_comment(vals)
    }
    try:
        q("""INSERT INTO market_snapshots(ts,total,strong_buy,strong_sell,buy_watch,sell_watch,wait_count,avg_confidence,best_symbol,best_name,best_signal,best_confidence,market_comment)
             VALUES(:ts,:total,:strong_buy,:strong_sell,:buy_watch,:sell_watch,:wait_count,:avg_confidence,:best_symbol,:best_name,:best_signal,:best_confidence,:market_comment)""", payload)
    except Exception:
        pass

def market(force=False):
    now=time.time()
    if not force and CACHE["market"] and now-CACHE["market_ts"]<60: return CACHE["market"]
    out={}
    for symbol,meta in load_symbols().items():
        if not meta.get("enabled",True): continue
        try:
            rows=fetch_chart(meta["ticker"])
            x=analyze(rows,meta); x["symbol"]=symbol; out[symbol]=x; log_decision(symbol,x)
        except Exception as e:
            out[symbol]={"symbol":symbol,"name":meta["name"],"ticker":meta["ticker"],"group":meta["group"],"error":str(e)}
    CACHE["market"]=out; CACHE["market_ts"]=now
    save_market_snapshot(out)
    return out

def trades_where(sql, params=None):
    return q("SELECT * FROM paper_trades " + sql, params or {}, fetch=True)

def trades_today(): return trades_where("WHERE day=:day ORDER BY id DESC", {"day":today()})
def trades_since(days):
    start=(date.today()-timedelta(days=days)).isoformat()
    return trades_where("WHERE day>=:start ORDER BY id DESC", {"start":start})
def all_trades(): return trades_where("ORDER BY id DESC")
def open_trades(): return trades_where("WHERE status='OPEN' ORDER BY id DESC")
def pnl_today(): return round(sum(float(x["pnl"]) for x in trades_today()),2)

def send_telegram(text_msg):
    token=os.getenv("TELEGRAM_BOT_TOKEN",""); chat_id=os.getenv("TELEGRAM_CHAT_ID","")
    if not token or not chat_id: return {"sent":False}
    try:
        r=requests.post(f"https://api.telegram.org/bot{token}/sendMessage",json={"chat_id":chat_id,"text":text_msg},timeout=10)
        return {"sent":r.ok}
    except Exception as e:
        return {"sent":False,"error":str(e)}

def update_open(snapshot):
    for t in open_trades():
        x=snapshot.get(t["symbol"])
        if not x or x.get("error"): continue
        price=float(x["price"]); side=t["side"]
        pnl=(price-t["entry"])*t["qty"] if side=="BUY" else (t["entry"]-price)*t["qty"]
        status="OPEN"
        if side=="BUY" and price<=t["stop"]: status="STOP_LOSS"
        if side=="BUY" and price>=t["target1"]: status="TAKE_PROFIT"
        if side=="SELL" and price>=t["stop"]: status="STOP_LOSS"
        if side=="SELL" and price<=t["target1"]: status="TAKE_PROFIT"
        closed=now_iso() if status!="OPEN" else None
        q("UPDATE paper_trades SET current_price=:price,pnl=:pnl,status=:status,closed_at=:closed WHERE id=:id",
          {"price":price,"pnl":round(pnl,2),"status":status,"closed":closed,"id":t["id"]})
        if status!="OPEN": send_telegram(f"Paper close {status}: {t['side']} {t['name']} PnL {round(pnl,2)} EUR")

def best_candidate(snapshot,settings):
    open_symbols={t["symbol"] for t in open_trades()}
    candidates=[]
    for symbol,x in snapshot.items():
        if x.get("error") or symbol in open_symbols: continue
        if x["signal"] not in ("STRONG BUY","STRONG SELL"): continue
        if x["confidence"]<settings["min_confidence"] or x["risk_reward"]<settings["min_risk_reward"]: continue
        if x["risk"]=="HIGH" and x["confidence"]<90: continue
        candidates.append(x)
    candidates.sort(key=lambda x:(x["confidence"],x["risk_reward"],-abs(x["change_5d"])),reverse=True)
    return candidates[0] if candidates else None

def record_engine(status,opened,message):
    q("INSERT INTO engine_runs(ts,status,opened_trade,message) VALUES(:ts,:status,:opened,:message)",
      {"ts":now_iso(),"status":status,"opened":1 if opened else 0,"message":message})

def run_cycle():
    with ENGINE_LOCK:
        settings=get_settings()
        snap=market(force=True); update_open(snap)
        p=pnl_today(); todays=trades_today(); opened=open_trades()
        checks=[(p>=settings["daily_target"],"STOP: daily target reached"),
                (p<=-settings["daily_max_loss"],"STOP: daily max loss reached"),
                (len(todays)>=int(settings["max_trades_per_day"]),"STOP: max trades reached"),
                (len(opened)>=int(settings["max_open_trades"]),"STOP: max open trades reached")]
        for cond,msg in checks:
            if cond:
                record_engine("STOP",False,msg)
                return {"executed":False,"status":msg,"daily_pnl":p}
        cand=best_candidate(snap,settings)
        if not cand:
            msg="No qualified professional setup"
            record_engine("WAIT",False,msg)
            return {"executed":False,"status":msg,"daily_pnl":p}
        risk_money=settings["account_size"]*settings["risk_per_trade_pct"]/100
        stop_dist=abs(cand["entry"]-cand["stop"])
        qty=risk_money/stop_dist if stop_dist>0 else 0
        q("""INSERT INTO paper_trades(day,opened_at,closed_at,symbol,name,group_name,side,entry,current_price,stop,target1,target2,qty,confidence,risk_reward,status,pnl,reason,ai_explanation)
             VALUES(:day,:opened_at,:closed_at,:symbol,:name,:group_name,:side,:entry,:current_price,:stop,:target1,:target2,:qty,:confidence,:risk_reward,:status,:pnl,:reason,:ai)""",
          {"day":today(),"opened_at":now_iso(),"closed_at":None,"symbol":cand["symbol"],"name":cand["name"],"group_name":cand["group"],
           "side":cand["side"],"entry":cand["entry"],"current_price":cand["price"],"stop":cand["stop"],"target1":cand["target1"],"target2":cand["target2"],
           "qty":qty,"confidence":cand["confidence"],"risk_reward":cand["risk_reward"],"status":"OPEN","pnl":0,"reason":cand["reason"],"ai":cand["ai_explanation"]})
        msg=f"Paper open: {cand['side']} {cand['name']} @ {cand['entry']} | SL {cand['stop']} | TP1 {cand['target1']} | conf {cand['confidence']}%"
        send_telegram(msg); record_engine("OPENED",True,msg)
        return {"executed":True,"status":msg,"candidate":cand,"daily_pnl":pnl_today()}

def report_for_trades(trades,title):
    total=len(trades); closed=[t for t in trades if t["status"]!="OPEN"]
    wins=[t for t in closed if float(t["pnl"])>0]; losses=[t for t in closed if float(t["pnl"])<0]
    pnl=round(sum(float(t["pnl"]) for t in trades),2)
    gross_win=sum(float(t["pnl"]) for t in wins); gross_loss=abs(sum(float(t["pnl"]) for t in losses))
    winrate=round(len(wins)/len(closed)*100,1) if closed else 0
    profit_factor=round(gross_win/gross_loss,2) if gross_loss>0 else (round(gross_win,2) if gross_win>0 else 0)
    best=max(trades,key=lambda x:float(x["pnl"]),default=None); worst=min(trades,key=lambda x:float(x["pnl"]),default=None)
    by={}
    for t in trades: by[t["symbol"]]=by.get(t["symbol"],0)+float(t["pnl"])
    top=max(by.items(),key=lambda x:x[1],default=None)
    return {"title":title,"total_trades":total,"closed_trades":len(closed),"open_trades":total-len(closed),"wins":len(wins),"losses":len(losses),
            "win_rate":winrate,"profit_factor":profit_factor,"pnl":pnl,
            "best_trade":dict(best) if best else None,"worst_trade":dict(worst) if worst else None,
            "top_symbol":{"symbol":top[0],"pnl":round(top[1],2)} if top else None,
            "comment":"Paper rezultat je pozitivan." if pnl>0 else "Paper rezultat je negativan ili neutralan; smanjiti rizik i pratiti kvalitet signala."}


def state_get(key, default=None):
    rows=q("SELECT value FROM automation_state WHERE key=:key", {"key":key}, fetch=True)
    if not rows:
        return default
    try:
        return json.loads(rows[0]["value"])
    except Exception:
        return rows[0]["value"]

def state_set(key, value):
    q("DELETE FROM automation_state WHERE key=:key", {"key":key})
    q("INSERT INTO automation_state(key,value) VALUES(:key,:value)", {"key":key,"value":json.dumps(value)})

def compact_report_text(report):
    return (
        f"{report['title']}\n"
        f"PnL: {report['pnl']} EUR\n"
        f"Trejdova: {report['total_trades']} | Open: {report['open_trades']}\n"
        f"Win rate: {report['win_rate']}% | Profit factor: {report['profit_factor']}\n"
        f"Top: {report['top_symbol']['symbol'] + ' ' + str(report['top_symbol']['pnl']) + ' EUR' if report.get('top_symbol') else '—'}\n"
        f"{report['comment']}"
    )

def maybe_send_scheduled_reports():
    settings=get_settings()
    now=datetime.now(timezone.utc)
    hour=int(settings.get("report_hour_utc",21))
    if now.hour < hour:
        return
    day_key=today()
    if settings.get("telegram_daily_report"):
        last=state_get("last_daily_report")
        if last != day_key:
            send_telegram("📊 Trading AI Daily Report\n\n" + compact_report_text(report_for_trades(trades_today(),"Daily Report")))
            state_set("last_daily_report", day_key)
            record_engine("REPORT", False, "Daily Telegram report processed")
    if settings.get("telegram_weekly_report") and now.weekday()==6:
        week_key=f"{now.isocalendar().year}-W{now.isocalendar().week}"
        last=state_get("last_weekly_report")
        if last != week_key:
            send_telegram("📈 Trading AI Weekly Report\n\n" + compact_report_text(report_for_trades(trades_since(7),"Weekly Report")))
            state_set("last_weekly_report", week_key)
            record_engine("REPORT", False, "Weekly Telegram report processed")

def engine_loop():
    while True:
        try:
            settings=get_settings()
            if settings.get("auto_engine_enabled"):
                run_cycle()
            maybe_send_scheduled_reports()
            time.sleep(max(60,int(settings.get("engine_interval_seconds",300))))
        except Exception as e:
            record_engine("ERROR",False,str(e))
            time.sleep(120)

threading.Thread(target=engine_loop,daemon=True).start()

class CapitalClient:
    def __init__(self):
        self.env=os.getenv("CAPITAL_ENV","demo")
        self.api_key=os.getenv("CAPITAL_API_KEY","")
        self.identifier=os.getenv("CAPITAL_IDENTIFIER","")
        self.password=os.getenv("CAPITAL_PASSWORD","")
        self.auto_trade=os.getenv("CAPITAL_AUTO_TRADE","false").lower()=="true"
    def status(self):
        return {"configured":bool(self.api_key and self.identifier and self.password),"env":self.env,"auto_trade":self.auto_trade,"safe_mode":not self.auto_trade}

@app.get("/api/market")
def api_market(): return market()

@app.get("/api/ai/market-brief")
def api_market_brief():
    rows=q("SELECT * FROM market_snapshots ORDER BY id DESC LIMIT 10", fetch=True)
    return {"snapshots": rows}

@app.get("/api/settings")
def api_settings(): return get_settings()

@app.post("/api/settings")
def api_save(payload:dict=Body(...)): return save_settings(payload)

@app.get("/api/paper/status")
def api_paper():
    snap=market(); update_open(snap)
    runs=q("SELECT * FROM engine_runs ORDER BY id DESC LIMIT 20", fetch=True)
    return {"day":today(),"daily_pnl":pnl_today(),"open":open_trades(),"trades":trades_today(),"engine_runs":runs}

@app.post("/api/paper/run-cycle")
def api_run(): return run_cycle()

@app.post("/api/paper/reset-day")
def api_reset():
    q("DELETE FROM paper_trades WHERE day=:day", {"day":today()})
    return {"ok":True,"daily_pnl":0}

@app.get("/api/report/daily")
def api_daily_report(): return report_for_trades(trades_today(),"Daily Report")

@app.get("/api/report/weekly")
def api_weekly_report(): return report_for_trades(trades_since(7),"Weekly Report")

@app.get("/api/report/all")
def api_all_report(): return report_for_trades(all_trades(),"All-Time Report")

@app.get("/api/export/trades.csv")
def api_export_csv():
    trades=all_trades()
    if not trades: return Response("", media_type="text/csv")
    keys=list(trades[0].keys())
    lines=[",".join(keys)]
    for t in trades:
        lines.append(",".join('"' + str(t.get(k,"")).replace('"','""') + '"' for k in keys))
    return Response("\n".join(lines), media_type="text/csv", headers={"Content-Disposition":"attachment; filename=trading_ai_trades.csv"})

@app.get("/api/automation/status")
def api_automation_status():
    settings=get_settings()
    rows=q("SELECT * FROM automation_state", fetch=True)
    return {
        "auto_engine_enabled": settings.get("auto_engine_enabled"),
        "interval_seconds": settings.get("engine_interval_seconds"),
        "telegram_daily_report": settings.get("telegram_daily_report"),
        "telegram_weekly_report": settings.get("telegram_weekly_report"),
        "report_hour_utc": settings.get("report_hour_utc"),
        "state": rows
    }

@app.post("/api/telegram/send-daily-report")
def api_send_daily_report():
    text_msg="📊 Trading AI Daily Report\n\n" + compact_report_text(report_for_trades(trades_today(),"Daily Report"))
    return send_telegram(text_msg)

@app.post("/api/telegram/send-weekly-report")
def api_send_weekly_report():
    text_msg="📈 Trading AI Weekly Report\n\n" + compact_report_text(report_for_trades(trades_since(7),"Weekly Report"))
    return send_telegram(text_msg)

@app.get("/api/capital/status")
def api_capital(): return CapitalClient().status()

@app.post("/api/test-alert")
def api_alert(): return send_telegram("Trading AI Elite 2.0: Telegram connected.")

app.mount("/", StaticFiles(directory="static", html=True), name="static")
