
import os,time,json,math,threading,requests
from datetime import datetime,timezone,date,timedelta
from pathlib import Path
from dotenv import load_dotenv
from fastapi import FastAPI,Body,Response
from fastapi.staticfiles import StaticFiles
from sqlalchemy import create_engine,text
load_dotenv(); APP_DIR=Path(__file__).parent; DATA_DIR=APP_DIR/'data'; DATA_DIR.mkdir(exist_ok=True)
DATABASE_URL=os.getenv('DATABASE_URL') or f"sqlite:///{DATA_DIR/'trading_ai_elite.db'}"
if DATABASE_URL.startswith('postgres://'): DATABASE_URL=DATABASE_URL.replace('postgres://','postgresql://',1)
engine=create_engine(DATABASE_URL,pool_pre_ping=True,future=True)
WATCHLIST_PATH=APP_DIR/'watchlist.json'; app=FastAPI(title='Trading AI Elite 1.0'); CACHE={'ts':0,'data':None}; LOCK=threading.Lock()
DEFAULT={'account_size':5000.0,'daily_target':50.0,'daily_max_loss':50.0,'risk_per_trade_pct':0.5,'max_trades_per_day':3,'max_open_trades':2,'min_confidence':78,'min_risk_reward':1.45,'auto_engine_enabled':False,'engine_interval_seconds':300,'trading_mode':'paper'}
def now(): return datetime.now(timezone.utc).isoformat()
def day(): return date.today().isoformat()
def q(sql,p=None,fetch=False):
    with engine.begin() as c:
        r=c.execute(text(sql),p or {})
        return [dict(x._mapping) for x in r.fetchall()] if fetch else None
def init():
    if DATABASE_URL.startswith('sqlite'):
        q('CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)')
        q('CREATE TABLE IF NOT EXISTS paper_trades(id INTEGER PRIMARY KEY AUTOINCREMENT,day TEXT,opened_at TEXT,closed_at TEXT,symbol TEXT,name TEXT,group_name TEXT,side TEXT,entry REAL,current_price REAL,stop REAL,target1 REAL,target2 REAL,qty REAL,confidence INTEGER,risk_reward REAL,status TEXT,pnl REAL,reason TEXT,ai_explanation TEXT)')
        q('CREATE TABLE IF NOT EXISTS decisions(id INTEGER PRIMARY KEY AUTOINCREMENT,ts TEXT,symbol TEXT,name TEXT,decision TEXT,confidence INTEGER,risk TEXT,price REAL,reason TEXT,ai_explanation TEXT)')
        q('CREATE TABLE IF NOT EXISTS engine_runs(id INTEGER PRIMARY KEY AUTOINCREMENT,ts TEXT,status TEXT,opened_trade INTEGER,message TEXT)')
    else:
        q('CREATE TABLE IF NOT EXISTS settings(key VARCHAR(100) PRIMARY KEY,value TEXT NOT NULL)')
        q('CREATE TABLE IF NOT EXISTS paper_trades(id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,day TEXT,opened_at TEXT,closed_at TEXT,symbol TEXT,name TEXT,group_name TEXT,side TEXT,entry DOUBLE PRECISION,current_price DOUBLE PRECISION,stop DOUBLE PRECISION,target1 DOUBLE PRECISION,target2 DOUBLE PRECISION,qty DOUBLE PRECISION,confidence INTEGER,risk_reward DOUBLE PRECISION,status TEXT,pnl DOUBLE PRECISION,reason TEXT,ai_explanation TEXT)')
        q('CREATE TABLE IF NOT EXISTS decisions(id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,ts TEXT,symbol TEXT,name TEXT,decision TEXT,confidence INTEGER,risk TEXT,price DOUBLE PRECISION,reason TEXT,ai_explanation TEXT)')
        q('CREATE TABLE IF NOT EXISTS engine_runs(id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,ts TEXT,status TEXT,opened_trade INTEGER,message TEXT)')
    for k,v in DEFAULT.items():
        if not q('SELECT key FROM settings WHERE key=:k',{'k':k},True): q('INSERT INTO settings(key,value) VALUES(:k,:v)',{'k':k,'v':json.dumps(v)})
init()
def settings():
    s=DEFAULT.copy()
    for r in q('SELECT key,value FROM settings',fetch=True):
        try:s[r['key']]=json.loads(r['value'])
        except Exception:s[r['key']]=r['value']
    s['engine_interval_seconds']=int(os.getenv('ENGINE_INTERVAL_SECONDS',s.get('engine_interval_seconds',300)))
    s['database_url_type']='postgresql' if DATABASE_URL.startswith('postgresql') else 'sqlite'; s['database_persistent']=bool(os.getenv('DATABASE_URL')); return s
def save_settings(p):
    for k,v in p.items():
        if k in DEFAULT: q('DELETE FROM settings WHERE key=:k',{'k':k}); q('INSERT INTO settings(key,value) VALUES(:k,:v)',{'k':k,'v':json.dumps(v)})
    return settings()
def symbols(): return json.load(open(WATCHLIST_PATH,encoding='utf-8'))['symbols']
def chart(ticker):
    r=requests.get(f'https://query1.finance.yahoo.com/v8/finance/chart/{ticker}',params={'range':'1y','interval':'1d'},headers={'User-Agent':'Mozilla/5.0'},timeout=15); r.raise_for_status(); res=r.json().get('chart',{}).get('result')
    if not res: raise ValueError('No market data')
    d=res[0]; qu=d['indicators']['quote'][0]; rows=[]
    for i,ts in enumerate(d['timestamp']):
        o,h,l,c=qu['open'][i],qu['high'][i],qu['low'][i],qu['close'][i]; v=qu.get('volume',[0]*len(d['timestamp']))[i]
        if None in (o,h,l,c): continue
        rows.append({'open':float(o),'high':float(h),'low':float(l),'close':float(c),'volume':float(v or 0)})
    if len(rows)<90: raise ValueError('Not enough history')
    return rows
def ema(a,n):
    alpha=2/(n+1); out=a[0]
    for v in a[1:]: out=alpha*v+(1-alpha)*out
    return out
def sma(a,n):
    b=a[-n:] if len(a)>=n else a; return sum(b)/len(b) if b else 0
def rsi(a,n=14):
    g=[]; l=[]
    for i in range(-n,0):
        ch=a[i]-a[i-1]; g.append(max(ch,0)); l.append(abs(min(ch,0)))
    ag=sum(g)/n; al=sum(l)/n; return 100 if al==0 else 100-100/(1+ag/al)
def atr(rows,n=14):
    trs=[]; prev=rows[-n-1]['close']
    for row in rows[-n:]: trs.append(max(row['high']-row['low'],abs(row['high']-prev),abs(row['low']-prev))); prev=row['close']
    return sum(trs)/len(trs)
def pct(a,n): return 0 if len(a)<=n else (a[-1]/a[-n-1]-1)*100
def analyze(rows,meta):
    c=[x['close'] for x in rows]; v=[x['volume'] for x in rows]; price=c[-1]; e8=ema(c[-60:],8); e20=ema(c[-80:],20); e50=ema(c[-160:],50); e200=ema(c,200); rv=rsi(c); av=atr(rows); mac=ema(c[-120:],12)-ema(c[-140:],26); ch5=pct(c,5); ch20=pct(c,20); ch60=pct(c,60); vol=sma(v,20); vf=v[-1]/vol if vol>0 else 1
    raw=50; bull=[]; bear=[]
    if price>e20: raw+=6; bull.append('price above EMA20')
    else: raw-=6; bear.append('price below EMA20')
    if e8>e20>e50: raw+=10; bull.append('bullish EMA stack')
    elif e8<e20<e50: raw-=10; bear.append('bearish EMA stack')
    if e50>e200: raw+=12; bull.append('primary trend bullish')
    else: raw-=12; bear.append('primary trend bearish')
    if mac>0: raw+=6; bull.append('MACD positive')
    else: raw-=6; bear.append('MACD negative')
    if 50<=rv<=66: raw+=8; bull.append('RSI healthy')
    elif rv>75: raw-=9; bear.append('RSI overbought')
    elif rv<35: raw-=9; bear.append('RSI weak')
    if ch5>0 and ch20>0: raw+=8; bull.append('5d and 20d momentum positive')
    elif ch5<0 and ch20<0: raw-=8; bear.append('5d and 20d momentum negative')
    raw += 5 if ch60>0 else -5
    if vf>1.4: raw+=3; bull.append('volume expansion')
    score=max(0,min(96,round(raw)))
    if score>=86: signal,side='STRONG BUY','BUY'
    elif score>=70: signal,side='BUY WATCH','BUY'
    elif score<=14: signal,side='STRONG SELL','SELL'
    elif score<=30: signal,side='SELL WATCH','SELL'
    else: signal,side='WAIT','WAIT'
    sd=max(av*1.5,price*.01); t1=max(av*2.2,price*.014); t2=max(av*3.4,price*.022)
    stop,target1,target2=(price+sd,price-t1,price-t2) if side=='SELL' else (price-sd,price+t1,price+t2)
    rr=abs(target1-price)/abs(price-stop) if abs(price-stop)>0 else 0; risk='LOW' if av/price<.025 else 'MEDIUM' if av/price<.055 else 'HIGH'; reason='; '.join((bull if side=='BUY' else bear) if side!='WAIT' else bull+bear)
    ai=f"{meta['name']}: {'WAIT' if side=='WAIT' else 'sistem bira '+('kupovinu' if side=='BUY' else 'prodaju')} | confidence {score}% | risk {risk} | RR 1:{round(rr,2)} | {reason}"
    return {'symbol':None,'name':meta['name'],'ticker':meta['ticker'],'group':meta['group'],'price':round(price,4),'signal':signal,'side':side,'confidence':int(score),'risk':risk,'trend':'BULLISH' if e50>e200 else 'BEARISH','rsi':round(rv,2),'atr':round(av,4),'macd':round(mac,4),'ema8':round(e8,4),'ema20':round(e20,4),'ema50':round(e50,4),'ema200':round(e200,4),'change_5d':round(ch5,2),'change_20d':round(ch20,2),'change_60d':round(ch60,2),'entry':round(price,4),'stop':round(stop,4),'target1':round(target1,4),'target2':round(target2,4),'risk_reward':round(rr,2),'reason':reason,'ai_explanation':ai,'candle':'N/A','updated_at':now()}
def log_decision(sym,x):
    try: q('INSERT INTO decisions(ts,symbol,name,decision,confidence,risk,price,reason,ai_explanation) VALUES(:ts,:s,:n,:d,:c,:r,:p,:re,:ai)',{'ts':now(),'s':sym,'n':x.get('name',''),'d':x.get('signal','ERR'),'c':x.get('confidence',0),'r':x.get('risk',''),'p':x.get('price',0),'re':x.get('reason',''),'ai':x.get('ai_explanation','')})
    except Exception: pass
def market(force=False):
    if not force and CACHE['data'] and time.time()-CACHE['ts']<60: return CACHE['data']
    out={}
    for sym,meta in symbols().items():
        if not meta.get('enabled',True): continue
        try: x=analyze(chart(meta['ticker']),meta); x['symbol']=sym; out[sym]=x; log_decision(sym,x)
        except Exception as e: out[sym]={'symbol':sym,'name':meta['name'],'ticker':meta['ticker'],'group':meta['group'],'error':str(e)}
    CACHE['data']=out; CACHE['ts']=time.time(); return out
def get_trades(where='',p=None): return q('SELECT * FROM paper_trades '+where,p or {},True)
def trades_today(): return get_trades('WHERE day=:d ORDER BY id DESC',{'d':day()})
def open_trades(): return get_trades("WHERE status='OPEN' ORDER BY id DESC")
def all_trades(): return get_trades('ORDER BY id DESC')
def trades_since(days): return get_trades('WHERE day>=:s ORDER BY id DESC',{'s':(date.today()-timedelta(days=days)).isoformat()})
def pnl_today(): return round(sum(float(x['pnl']) for x in trades_today()),2)
def send_telegram(msg):
    tok=os.getenv('TELEGRAM_BOT_TOKEN',''); chat=os.getenv('TELEGRAM_CHAT_ID','')
    if not tok or not chat: return {'sent':False}
    try: return {'sent':requests.post(f'https://api.telegram.org/bot{tok}/sendMessage',json={'chat_id':chat,'text':msg},timeout=10).ok}
    except Exception as e: return {'sent':False,'error':str(e)}
def update_open(snap):
    for t in open_trades():
        x=snap.get(t['symbol'])
        if not x or x.get('error'): continue
        price=float(x['price']); side=t['side']; pnl=(price-t['entry'])*t['qty'] if side=='BUY' else (t['entry']-price)*t['qty']; status='OPEN'
        if side=='BUY' and price<=t['stop']: status='STOP_LOSS'
        if side=='BUY' and price>=t['target1']: status='TAKE_PROFIT'
        if side=='SELL' and price>=t['stop']: status='STOP_LOSS'
        if side=='SELL' and price<=t['target1']: status='TAKE_PROFIT'
        q('UPDATE paper_trades SET current_price=:p,pnl=:pnl,status=:st,closed_at=:cl WHERE id=:id',{'p':price,'pnl':round(pnl,2),'st':status,'cl':now() if status!='OPEN' else None,'id':t['id']})
        if status!='OPEN': send_telegram(f"Paper close {status}: {t['side']} {t['name']} PnL {round(pnl,2)} EUR")
def best_candidate(snap,s):
    opened={t['symbol'] for t in open_trades()}; arr=[]
    for sym,x in snap.items():
        if x.get('error') or sym in opened: continue
        if x['signal'] not in ('STRONG BUY','STRONG SELL'): continue
        if x['confidence']<s['min_confidence'] or x['risk_reward']<s['min_risk_reward']: continue
        if x['risk']=='HIGH' and x['confidence']<90: continue
        arr.append(x)
    arr.sort(key=lambda x:(x['confidence'],x['risk_reward']),reverse=True); return arr[0] if arr else None
def engine_log(st,op,msg): q('INSERT INTO engine_runs(ts,status,opened_trade,message) VALUES(:ts,:s,:o,:m)',{'ts':now(),'s':st,'o':1 if op else 0,'m':msg})
def run_cycle():
    with LOCK:
        s=settings(); snap=market(True); update_open(snap); p=pnl_today(); tt=trades_today(); ot=open_trades()
        for cond,msg in [(p>=s['daily_target'],'STOP: daily target reached'),(p<=-s['daily_max_loss'],'STOP: daily max loss reached'),(len(tt)>=int(s['max_trades_per_day']),'STOP: max trades reached'),(len(ot)>=int(s['max_open_trades']),'STOP: max open trades reached')]:
            if cond: engine_log('STOP',False,msg); return {'executed':False,'status':msg,'daily_pnl':p}
        c=best_candidate(snap,s)
        if not c: msg='No qualified professional setup'; engine_log('WAIT',False,msg); return {'executed':False,'status':msg,'daily_pnl':p}
        qty=(s['account_size']*s['risk_per_trade_pct']/100)/abs(c['entry']-c['stop'])
        q('INSERT INTO paper_trades(day,opened_at,closed_at,symbol,name,group_name,side,entry,current_price,stop,target1,target2,qty,confidence,risk_reward,status,pnl,reason,ai_explanation) VALUES(:day,:oa,:ca,:sym,:name,:grp,:side,:entry,:cur,:stop,:t1,:t2,:qty,:conf,:rr,:status,:pnl,:reason,:ai)',{'day':day(),'oa':now(),'ca':None,'sym':c['symbol'],'name':c['name'],'grp':c['group'],'side':c['side'],'entry':c['entry'],'cur':c['price'],'stop':c['stop'],'t1':c['target1'],'t2':c['target2'],'qty':qty,'conf':c['confidence'],'rr':c['risk_reward'],'status':'OPEN','pnl':0,'reason':c['reason'],'ai':c['ai_explanation']})
        msg=f"Paper open: {c['side']} {c['name']} @ {c['entry']} | SL {c['stop']} | TP1 {c['target1']} | conf {c['confidence']}%"; send_telegram(msg); engine_log('OPENED',True,msg); return {'executed':True,'status':msg,'candidate':c,'daily_pnl':pnl_today()}
def report(trades,title):
    closed=[t for t in trades if t['status']!='OPEN']; wins=[t for t in closed if float(t['pnl'])>0]; losses=[t for t in closed if float(t['pnl'])<0]; pnl=round(sum(float(t['pnl']) for t in trades),2); gw=sum(float(t['pnl']) for t in wins); gl=abs(sum(float(t['pnl']) for t in losses)); by={}
    for t in trades: by[t['symbol']]=by.get(t['symbol'],0)+float(t['pnl'])
    top=max(by.items(),key=lambda x:x[1],default=None); best=max(trades,key=lambda x:float(x['pnl']),default=None); worst=min(trades,key=lambda x:float(x['pnl']),default=None)
    return {'title':title,'total_trades':len(trades),'closed_trades':len(closed),'open_trades':len(trades)-len(closed),'wins':len(wins),'losses':len(losses),'win_rate':round(len(wins)/len(closed)*100,1) if closed else 0,'profit_factor':round(gw/gl,2) if gl>0 else 0,'pnl':pnl,'best_trade':dict(best) if best else None,'worst_trade':dict(worst) if worst else None,'top_symbol':{'symbol':top[0],'pnl':round(top[1],2)} if top else None,'comment':'Paper rezultat je pozitivan.' if pnl>0 else 'Paper rezultat je negativan ili neutralan.'}
def loop():
    while True:
        try:
            s=settings()
            if s.get('auto_engine_enabled'): run_cycle()
            time.sleep(max(60,int(s.get('engine_interval_seconds',300))))
        except Exception as e: engine_log('ERROR',False,str(e)); time.sleep(120)
threading.Thread(target=loop,daemon=True).start()
@app.get('/api/market')
def api_market(): return market()
@app.get('/api/settings')
def api_settings(): return settings()
@app.post('/api/settings')
def api_save(payload:dict=Body(...)): return save_settings(payload)
@app.get('/api/paper/status')
def api_paper():
    snap=market(); update_open(snap); return {'day':day(),'daily_pnl':pnl_today(),'open':open_trades(),'trades':trades_today(),'engine_runs':q('SELECT * FROM engine_runs ORDER BY id DESC LIMIT 20',fetch=True)}
@app.post('/api/paper/run-cycle')
def api_run(): return run_cycle()
@app.post('/api/paper/reset-day')
def api_reset(): q('DELETE FROM paper_trades WHERE day=:d',{'d':day()}); return {'ok':True,'daily_pnl':0}
@app.get('/api/report/daily')
def api_daily(): return report(trades_today(),'Daily Report')
@app.get('/api/report/weekly')
def api_weekly(): return report(trades_since(7),'Weekly Report')
@app.get('/api/report/all')
def api_all(): return report(all_trades(),'All-Time Report')
@app.get('/api/export/trades.csv')
def export_csv():
    t=all_trades()
    if not t: return Response('',media_type='text/csv')
    keys=list(t[0].keys()); lines=[','.join(keys)]
    for r in t: lines.append(','.join('"'+str(r.get(k,'')).replace('"','""')+'"' for k in keys))
    return Response('\n'.join(lines),media_type='text/csv',headers={'Content-Disposition':'attachment; filename=trading_ai_trades.csv'})
@app.get('/api/capital/status')
def cap(): return {'configured':bool(os.getenv('CAPITAL_API_KEY') and os.getenv('CAPITAL_IDENTIFIER') and os.getenv('CAPITAL_PASSWORD')),'env':os.getenv('CAPITAL_ENV','demo'),'auto_trade':os.getenv('CAPITAL_AUTO_TRADE','false').lower()=='true','safe_mode':os.getenv('CAPITAL_AUTO_TRADE','false').lower()!='true'}
@app.post('/api/test-alert')
def alert(): return send_telegram('Trading AI Elite 1.0: Telegram connected.')
app.mount('/',StaticFiles(directory='static',html=True),name='static')
